version: "3.8"
services:
  app-logger:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-logger
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      MONGO_URI: ${MONGO_URI:-mongodb://crane-logger:password@logger-mongo-db:27017/admin}
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app
    depends_on:
      - logger-mongo-db
    links:
      - logger-mongo-db


  logger-mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: crane-logger
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGODB_DATA_DIR: /data/db
    ports:
      - "${MONGO_PORT:-27001}:27017"
    volumes:
      - logger-mongo-data:/data/db

volumes:
  logger-mongo-data:  
