version: "3.8"
services:
  app-logger:
    restart: always
    build: .
    container_name: app-logger
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      APP_PORT: 8000  
      MONGO_URI: mongodb://localhost:27017/ 
      MONGO_PORT: 27017 
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app


  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME  
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD  
      MONGO_PORT: 27001
    ports:
      - "${MONGO_PORT:-27001}:27017"
    volumes:
      - cc-logger-mongo-data:/data/db


volumes:
  cc-logger-mongo-data:  
