{{- if .Values.redis.create -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    {{- include "cranecloud.labels" . | nindent 4 }}
spec:
  serviceName: redis
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: {{ .Values.redis.port }}
          name: redis
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.redis.storage }}
{{- end }}
