replicaCount: 1

image:
  repository: cranecloud/activity-logger
  pullPolicy: Always
  tag: ${{ DOCKER_IMAGE_TAG }}

nameOverride: "activity-logger"

nginxConf:
  server {
        listen 80;

        location / {
            proxy_pass http://localhost:8000/;
        }
    }

port: 8000

environment:
  JWT_SALT: ${{ JWT_SALT }}
  MONGO_URI: ${{ MONGO_URI }}
  FASTAPI_ENV: production
  REDIS_URL: redis://redis:6379

celery:
  create: true
  command: 
    - "poetry"
    - "run"
    - "celery"
    - "-A"
    - "main.celery"
    - "worker"
    - "--loglevel=info"
  port: 5001

redis:
  create: false

mongo:
  create: true